modLoader="javafml"
loaderVersion="[1,)"
license="MIT"

[[mods]]
modId="sharingan"
version="1.0.0"
displayName="Sharingan"
description='''Adiciona somente o Sharingan (1, 2 e 3 tomoe), o Mangekyou Sharingan (Itachi, Sasuke, Obito, Shisui) e o Mangekyou Eterno.'''

[[dependencies.sharingan]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.sharingan]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"
